### ISSUE TITLE
Requesting To Add Patterns In Java

### ISSUE THREAD

**Issue by arun-jain-dev** [aryashah2k/Programming-Patterns-And-Designs#1]
Hi, I loved your work so far and have got a hang of what you are trying to accomplish. I would like to contribute this repository by creating a whole new branch dedicated to all these patterns in Java Programming Language

**Comment by aryashah2k** [comment]
Thanks for reaching out Arun, you can definitely contribute to this repository with Java programs for the existing patterns or any new ones you wish to add. Fork the project, create a branch and let me know when you make your first pull request! All the best and thanks for showing interest...
